[package]
name = "npm-expansions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
tempdir = "0.3.7"
test-case = "3.0.0"
