version: "3.9"

services:
  webserver:
    container_name: npm-expansions-web-server
    hostname: npm-expansions
    build: ./npm-expansions
    expose:
      - "8000"
  reverse-proxy:
    container_name: npm-expansions-reverse-proxy
    hostname: reverse
    build: ./nginx-reverse-proxy
    ports:
      - 80:80
      - 443:443