version: "3.9"

services:
  reverse-proxy:
    container_name: npm-expansions-reverse-proxy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    hostname: reverse
    build: 
      context: ./nginx-reverse-proxy
      args:
        NGINX_CONFIG: npm-expansions.dev.conf
        UMAMI_WEBSITE_ID: 123
        UMAMI_WEBSITE_URL: abc
    volumes:
      - type: bind
        source: ./nginx-reverse-proxy/pages
        target: /etc/nginx/pages
      - type: bind
        source: ./nginx-reverse-proxy/static
        target: /etc/nginx/static
    ports:
      - 8080:8080