[package]
name = "npm-expansions-static"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
minifier = "0.2.2"
minify-html = "0.10.8"