name: Fly Deploy

on:
  push:
    branches: [main]

jobs:
  deploy-npm-expansions:
    runs-on: ubuntu-latest
    concurrency: deploy-npm-expansions
    defaults:
      run:
        working-directory: npm-expansions
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-nginx-reverse-proxy:
    runs-on: ubuntu-latest
    concurrency: deploy-nginx-reverse-proxy
    defaults:
      run:
        working-directory: nginx-reverse-proxy
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
