name: Style Check
on:
  push:
    branches: [main]
jobs:
  style_check_web_server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./npm-expansions
    steps:
      - uses: actions/checkout@v3

      - name: Install toolchain
        run: rustup update nightly-2023-03-28 && rustup default nightly-2023-03-28

      - name: Cargo Format Check
        run: cargo fmt -- --check

      - name: Cargo Clippy Check
        run: cargo clippy
  style_check_reverse_proxy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./nginx-reverse-proxy
    steps:
      - uses: actions/checkout@v3

      - name: Install toolchain
        run: rustup update nightly-2023-03-28 && rustup default nightly-2023-03-28

      - name: Cargo Format Check
        run: cargo fmt -- --check

      - name: Cargo Clippy Check
        run: cargo clippy