name: Unit Tests
on:
  push:
    branches: [main]
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Navigate to server
        run: cd npm-expansions

      - name: Cargo Test
        run: cd npm-expansions-server && cargo test